LAYER_BACKGROUND_COVER = -2
LAYER_STAGE_COVER = -1
LAYER_STAGE = 0
LAYER_COVER = 1
LAYER_STAGE_LANE = 1.5
LAYER_JUDGMENT_LINE = 2
LAYER_SLOT_EFFECT = 3

LAYER_BEAT_LINE = 10
LAYER_ACTIVE_SIDE_CONNECTOR_BOTTOM = 11
LAYER_GUIDE_CONNECTOR_BOTTOM = 12
LAYER_ACTIVE_SIDE_CONNECTOR_TOP = 13
LAYER_GUIDE_CONNECTOR_TOP = 14
LAYER_PREVIEW_COVER = 15
LAYER_SIM_LINE = 16
LAYER_TIME_LINE = 17
LAYER_BPM_LINE = 18
LAYER_TIMESCALE_LINE = 19

LAYER_NOTE_SLIM_BODY = 20
LAYER_NOTE_FLICK_BODY = 21
LAYER_NOTE_BODY = 22
LAYER_NOTE_TICK = 23
LAYER_NOTE_ARROW = 24
LAYER_SLOT_GLOW_EFFECT = 25

LAYER_DAMAGE = 50
LAYER_JUDGMENT = 51


def get_z(layer: int | float, time: float = 0.0, lane: float = 0.0, etc: int | float = 0.0) -> float:
    time = round(time, 3)
    lane = round(lane, 2)
    return ((1 / 100) * etc) + abs(lane) - (10000 * time) + (65540000 * layer)
